service: generatePdf

package:
  exclude:
    -node-modules/**
    -./**
  include:
    -build/**

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-iam-roles-per-function

functions:
  app:
    handler: build/src/index.handler
    events:
      - http:
          path: /send-pdf
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "s3:Put*"
          - "ses:*"
        Resource:
          - arn:aws:s3:::pdfs.christee/*
          - arn:aws:ses:us-east-1:*:*
