service: generatePdf

package:
  exclude:
    -./**
  include:
    -node-modules/**
    -build/**

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-iam-roles-per-function

functions:
  app:
    handler: build/src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "s3:Put*"
        Resource: arn:aws:s3:::pdfs.christee/*