/*
 * Copyright 2020-2021 AskChristee, LLC. All rights reserved.
 */

import { TResponseMeta } from '.';

export type TBudgetCalc = {
    alimony: number,
    area: string,
    auto_ins: number,
    c_cards: number,
    c_care: number,
    c_phone: number,
    c_support: number,
    cable: number,
    car_pay: number,
    coll_debt: number,
    dis_food: string,
    dis_mtge: string,
    dis_util: string,
    f_momey: number,
    f_money_per: number,
    food: number,
    fumess: string,
    health_ins: number,
    ltv: number,
    ma: number,
    med_with: number,
    mfed_taxes: number,
    mstate_tax: number,
    other_amt: number,
    otherd: string,
    pets: number,
    report_type: string,
    retire: number,
    sp: number,
    ss_with: number,
    state_sel: string,
    t_piti: number,
    temp_mi: number,
    temp_pi: number,
    temp_rate: number,
    total_exp_per: number,
    total_exp: number,
    total_mtge: number,
    utilities: number
}

export type TBudgetPDF = {
    alimony: number,
    area: string,
    auto_ins: number,
    c_cards: number,
    c_care: number,
    c_phone: number,
    c_support: number,
    cable: number,
    cal_fr: number,
    car_pay: number,
    coll_debt: number,
    condo: number,
    dis_food: string,
    dis_mtge: string,
    dis_util: string,
    f_momey: number,
    f_money_per: number,
    food: number,
    fumess: string,
    health_ins: number,
    input_ltv_yes: number,
    input_ma: number,
    inputcred: number,
    ltv: number,
    ma: number,
    med_rate: number,
    med_with: number,
    mfed_taxes: number,
    mstate_tax: number,
    net_mort_pay: number,
    other_amt: number,
    otherd: string,
    pdf_bottom: string,
    pdf_h4: string,
    pdf_h5:  string,
    pdf_head1: string,
    pdf_head2: string,
    pdfmess1: string,
    pdfmess2: string,
    pets: number,
    print_t_bracket: number,
    q_income: number,
    report_type:string,
    retire: number,
    sp: number,
    ss_rate: number,
    ss_with: number,
    state_sel: string,
    stax_rate: number,
    t_piti: number,
    tax_saving: number,
    tdebt_per: number,
    temp_ins: number,
    temp_mi: number,
    temp_pi: number,
    temp_pt: number,
    temp_rate: number,
    tfree_income: number,
    tot_duct: number,
    tot_monthy: number,
    total_debts: number,
    total_exp_per: number,
    total_exp: number,
    total_mtge: number,
    total_taxes: number,
    ttax_per: number,
    utilities: number,
    va_fee_ex: string
}

export type TBudgetResponse = {
    meta: TResponseMeta,
    calc: TBudgetCalc,
    pdf: TBudgetPDF,
};