/*
 * Copyright 2020-2021 AskChristee, LLC. All rights reserved.
 */

import { TResponseMeta } from "./";

export type TBQParams = {
    pForm: TBQPForm
}

export type TBQPForm = {
    doType: string[],
    doconv: string,
    dofha: string,
    dova: string,
    dousda: string,
    t_cash: number,
    q_income: number,
    m_debts: number,
    int_rate: number,
    s_cred: number,
    filing_status: string,
    county_select: number,
    state: string,
    report_summary: string,
    display_ccost: string,
    display_pdf_output: string,
    inputcred: number,
    lim_piti: number,
    input_ltv: number,
    ftbuyer: string,
    term: number,
    va_fee_ex: string,
    cashre: string,
    input_scred: number,
    use_ratios: string,
    input_uw_fee: number,
    org_fee: number,
    condo: number,
    input_pmi$: string,
    lend_cred: number
}

export type TBQACalc = {
    allow_piti: number,
    area: string,
    cal_br: number,
    cal_fr: number,
    condo: number,
    d_payment: number,
    dol_cred: number,
    dol_lend: number,
    ex_cash: number,
    fumess: string,
    ltv: number,
    lim_piti: number,
    ma: number,
    net_mort_pay: number,
    print_t_bracket: number,
    r_cash: number,
    ratio_string: string,
    report_type: string,
    sp: number,
    state_sel: string,
    t_cash: number,
    t_piti: number,
    target_piti: number,
    tax_saving: number,
    temp_cred: number,
    temp_lend: number,
    temp_ins: number,
    temp_mi: number,
    temp_pi: number,
    temp_pt: number,
    temp_rate: number,
    tot_duct: number,
    total_mtge: number,
    totalcc: number
};

export type TBQAClose = {
    sp: number,
    area: string,
    state_sel: string,
    current_date: string,
    est_close: string,
    first_payment: string,
    app_fee: number,
    home_ins: number,
    cred_rpt: number,
    flood_cert: number,
    pest_ins: number,
    underfee: number,
    loan_org$: string,
    abs_fee: number,
    clo_fee: number,
    ins_tit: number,
    survey: number,
    int_int: number,
    days_interest: number,
    haz_insur$: string,
    escrow_tax: number,
    clo_tax: number,
    net_tax: number,
    transfer: number,
    docstamp: number,
    mtgetax: number,
    clerk_office: number,
    totalcc: number,
    s_credit$: string,
    l_credit$: string,
    total_cred: number,
    d_payment: number,
    r_cash: number,
    tax_period$: string,
    p_tax_adj$: string,
    tax_escrow_date: string,
    tax_escrow: number
};

export type TBQANotes = {
    allow_piti: number,
    area: string,
    cal_br: number,
    cal_fr: number,
    condo: number,
    d_payment: number,
    dol_cred: number,
    ex_cash: number,
    fumess: string,
    ltv: number,
    ma: number,
    net_mort_pay: number,
    pdf_head1: string,
    pdf_head2: string,
    pdfmess1: string,
    pdfmess2: string,
    pdfmess3: string,
    pdfmess4: string,
    pdfmess5: string,
    pdfmess6: string,
    pdfmess7: string,
    pdfmess8: string,
    pdfmess9: string,
    pdfmess10: string,
    pdfmess11: string,
    pdfmess12: string,
    pdf_botton: string,
    print_t_bracket: number,
    r_cash: number,
    ratio_string: string,
    ratios_used: string,
    report_type: string,
    sp: number,
    state_sel: string,
    tax_saving: number,
    t_cash: number,
    t_piti: number,
    target_piti: number,
    temp_cred: number,
    temp_ins: number,
    temp_lend: number,
    temp_mi: number,
    temp_pi: number,
    temp_pt: number,
    temp_rate: number,
    tot_duct: number,
    total_mtge: number,
    totalcc: number
};

export type TBQBCalc = TBQACalc;

export type TBQBClose = {
    sp: number,
    area: string,
    state_sel: string,
    current_date: string,
    est_close: string,
    first_payment: string,
    app_fee: number,
    home_ins: number,
    cred_rpt: number,
    flood_cert: number,
    pest_ins: number,
    underfee: number,
    loan_org$: string,
    abs_fee: number,
    clo_fee: number,
    ins_tit: number,
    survey: number,
    int_int: number,
    days_interest: number,
    haz_insur$: string,
    escrow_tax: number,
    clo_tax: number,
    net_tax: number,
    transfer: number,
    docstamp: number,
    mtgetax: number,
    clerk_office: number,
    totalcc: number,
    s_credit$: string,
    l_credit$: string,
    total_cred: number,
    d_payment: number,
    r_cash: number,
    tax_period$: string,
    p_tax_adj$: string,
    tax_escrow_date: string,
    tax_escrow: number
};

export type TBQBNotes = TBQANotes;


export type TBuyerQualResponseObject = {
    aCalc: TBQACalc,
    aClose: TBQAClose,
    aNotes: TBQANotes,
    bCalc: TBQBCalc | undefined,
    bClose: TBQBClose | undefined,
    bNotes: TBQBNotes | undefined,
};

export type TBuyerQualResponse = {
    meta: TResponseMeta,
    params: TBQParams,
    conventional: TBuyerQualResponseObject,
    fha: TBuyerQualResponseObject,
    va: TBuyerQualResponseObject,
    usda: TBuyerQualResponseObject
};
