import { TResponseMeta } from ".";

export type TACalc = {
    state_sel: string,
    report_type: string,
    fumess: string,
    ratio_string: string,
    area: string,
    target_piti: number,
    sp: number,
    ma: number,
    ltv: number,
    total_mtge: number,
    d_payment: number,
    totalcc: number,
    dol_cred: number,
    temp_cred: number,
    dol_lend: number,
    temp_lend: number,
    r_cash: number,
    t_cash: number,
    ex_cash: number,
    temp_rate: number,
    t_piti: number,
    temp_mi: number,
    temp_pt: number,
    temp_ins: number,
    condo: number,
    tot_duct: number,
    net_mort_pay: number,
    temp_pi: number,
    print_t_bracket: number,
    tax_saving: number,
    cal_br: number,
    cal_fr: number
};

export type TAClose = {
    sp: number,
    area: string,
    state_sel: string,
    current_date: string,
    est_close: string,
    first_payment: string,
    app_fee: number,
    home_ins: number,
    cred_rpt: number,
    flood_cert: number,
    pest_ins: number,
    underfee: number,
    loan_org$: string,
    abs_fee: number,
    clo_fee: number,
    ins_tit: number,
    survey: number,
    int_int: number,
    days_interest: number,
    haz_insur$: string,
    escrow_tax: number,
    clo_tax: number,
    net_tax: number,
    transfer: number,
    docstamp: number,
    mtgetax: number,
    clerk_office: number,
    totalcc: number,
    s_credit$: string,
    l_credit$: string,
    total_cred: number,
    d_payment: number,
    r_cash: number,
    tax_period$: string,
    p_tax_adj$: string,
    tax_escrow_date: string,
    tax_escrow: number
};

export type TANotes = {
    state_sel: string,
    report_type: string,
    fumess: string,
    ratio_string: string,
    area: string,
    target_piti: 0,
    sp: 12345,
    ma: 0,
    ltv: 0,
    total_mtge: 0,
    d_payment: 12345,
    totalcc: 1095,
    dol_cred: 0,
    temp_cred: 0.00,
    dol_lend: 0,
    temp_lend: 0.00,
    r_cash: 13440,
    t_cash: 0,
    ex_cash: 0,
    temp_rate: 3,
    t_piti: 0,
    temp_mi: 0,
    temp_pt: 13.77,
    temp_ins: 2.42,
    condo: 0,
    tot_duct: 165,
    print_t_bracket: 10,
    tax_saving: 1.37,
    net_mort_pay: 0,
    cal_fr: 0,
    cal_br: 0,
    pdfmess: string,
    pdf_head1: string,
    pdf_head2: string,
    pdfmess1: string,
    pdfmess2: string,
    pdfmess3: string,
    pdfmess4: string,
    pdfmess5: string,
    pdfmess6: string,
    pdfmess7: string,
    pdfmess8: string,
    pdfmess9: string,
    pdfmess10: string,
    pdfmess11: string,
    pdfmess12: string,
    pdfmess13: string,
    pdf_bottom: string
};

export type TBCalc = TACalc;

export type TBClose = {
    sp: number,
    area: string,
    state_sel: string,
    current_date: string,
    est_close: string,
    first_payment: string,
    app_fee: number,
    home_ins: number,
    cred_rpt: number,
    flood_cert: number,
    pest_ins: number,
    underfee: number,
    loan_org$: string,
    abs_fee: number,
    clo_fee: number,
    ins_tit: number,
    survey: number,
    int_int: number,
    days_interest: number,
    haz_insur$: string,
    escrow_tax: number,
    clo_tax: number,
    net_tax: number,
    transfer: number,
    docstamp: number,
    mtgetax: number,
    clerk_office: number,
    totalcc: number,
    s_credit$: string,
    l_credit$: string,
    total_cred: number,
    d_payment: number,
    r_cash: number,
    tax_period$: string,
    p_tax_adj$: string,
    tax_escrow_date: string,
    tax_escrow: number
};

export type TBNotes = {
    state_sel: string,
    report_type: string,
    fumess: string,
    ratio_string: string,
    area: string,
    target_piti: number,
    sp: number,
    ma: number,
    ltv: number,
    total_mtge: number,
    d_payment: number,
    totalcc: number,
    dol_cred: number,
    temp_cred: number,
    dol_lend: number,
    temp_lend: number,
    r_cash: number,
    t_cash: number,
    ex_cash: number,
    temp_rate: number,
    t_piti: number,
    temp_mi: number,
    temp_pt: number,
    temp_ins: number,
    condo: number,
    tot_duct: number,
    print_t_bracket: number,
    tax_saving: number,
    net_mort_pay: number,
    cal_fr: number,
    cal_br: number,
    pdfmess: string,
    pdf_head1: string,
    pdf_head2: string,
    pdfmess1: string,
    pdfmess2: string,
    pdfmess3: string,
    pdfmess4: string,
    pdfmess5: string,
    pdfmess6: string,
    pdfmess7: string,
    pdfmess8: string,
    pdfmess9: string,
    pdfmess10: string,
    pdfmess11: string,
    pdfmess12: string,
    pdfmess13: string,
    pdf_bottom: string
}

export type TBuyersChoiceResponseObject = {
    aCalc: TACalc,
    aClose: TAClose,
    aNotes: TANotes,
    bCalc: TBCalc | undefined,
    bClose: TBClose | undefined,
    bNotes: TBNotes | undefined,
};

export type TBuyersChoiceResponse = {
    meta: TResponseMeta,
    conventional: TBuyersChoiceResponseObject,
    fha: TBuyersChoiceResponseObject,
    va: TBuyersChoiceResponseObject,
    usda: TBuyersChoiceResponseObject
};
