import { TResponseMeta } from '.';

export type TClosingCostBrowser = {
  brwmess1: string;
  brwmess2: string;
  brwmess3: string;
  brwmess4: string;
  brwmess5: string;
  brwmess6: string;
  brwmess7: string;
  brwmess8: string;
  brwmess9: string;
  brwmess10: string;
  brwmess11: string;
  brwmess12: string;
  brwmess13: string;
  brwmess14: string;
  brwmess15: string;
  brwmess16: string;
  brwmess17: string;
  brwmess18: string;
  brwmess19: string;
  brwmess20: string;
  brwmess21: string;
  brwmess22: string;
  brwmess23: string;
  brwmess24: string;
  brwmess25: string;
  brwmess26: string;
  brwmess27: string;
  brwmess28: string;
  brwmess29: string;
  brwmess30: string;
  brwmess31: string;
  brwmess32: string;
};

export type TClosingCostPdf = {
  pdfmess1: string;
  pdfmess2: string;
  pdfmess2a: string;
  pdfmess3: string;
  pdfmess3a: string;
  pdfmess3ab: string;
  pdfmess4: string;
  pdfmess5: string;
  pdfmess6: string;
  pdfmess7: string;
  pdfmess8: string;
  pdfmess9: string;
  pdfmess10: string;
  pdfmess11: string;
  pdfmess12: string;
  pdfmess13: string;
  pdfmess14: string;
  pdfmess15: string;
  pdfmess16: string;
  pdfmess17: string;
  pdfmess18: string;
  pdfmess19: string;
  pdfmess20: string;
  pdfmess21: string;
  pdfmess22: string;
  pdfmess23: string;
  pdfmess24: string;
  pdfmess25: string;
  pdfmess26: string;
  pdfmess27: string;
  pdfmess28: string;
  pdfmess29: string;
  pdfmess30: string;
  pdfmess31: string;
  pdfmess32: string;
  pdfmess33: string;
  pdfmess34: string;
  pdfmess35: string;
  pdfmess36: string;
  pdfmess37: string;
  pdfmess38: string;
  pdfmess39: string;
};

export type TClosingCostResponse = {
  meta: TResponseMeta;
  browser: TClosingCostBrowser;
  pdf: TClosingCostPdf;
};
