/*
 * Copyright 2020-2021 AskChristee, LLC. All rights reserved.
 */

/*
 * Copyright 2020-2021 AskChristee, LLC. All rights reserved.
 */

import { TResponseMeta } from '.';

export type TInvestmentCalc = {
    report_type: string,
    state_sel: string,
    area: string,
    sp: number,
    d_payment: number,
    totalcc: number,
    dol_cred: number,
    temp_cred: string,
    r_cash: number,
    acq_cost: number,
    ma: number,
    ltv: number,
    temp_rate: string,
    t_piti: number,
    avg_mo_rent: string,
    noi: number,
    debt_ser: number,
    cash_flow_$: string,
    cash_flow: number,
    h_value: number,
    ma_bal: number,
    net_equity: number,
    avg_deprec: number,
    gross_profit: number,
    capital_gain: number,
    net_profits: number,
    cash_$: string,
    cash_imp: number,
    tax_sit: string,
    tot_duct: number,
    tax_due$: string,
    tax_saving: number
}

export type TInvestmentClose = {
    sp: number,
    area: string,
    state_sel: string,
    current_date: string,
    est_close: string,
    first_payment: string,
    app_fee: number,
    home_ins: number,
    cred_rpt: number,
    flood_cert: number,
    pest_ins: number,
    underfee: number,
    loan_org$: string,
    abs_fee: number,
    clo_fee: number,
    ins_tit: string,
    survey: number,
    int_int: string,
    days_interest: number,
    haz_insur$: string,
    escrow_tax: string,
    clo_tax: string,
    net_tax: string,
    transfer: string,
    docstamp: string,
    mtgetax: string,
    clerk_office: number,
    totalcc: number,
    s_credit$: string,
    l_credit$: string,
    total_cred: number,
    d_payment: number,
    r_cash: number,
    tax_period$: string,
    p_tax_adj$: string,
    tax_escrow_date: string,
    tax_escrow: number
}

export type TInvestmentPDF = {
    acq_cost: number,
    an_deprec: number,
    area: string,
    avg_deprec: number,
    avg_rent: number,
    cap_gain_rate: number,
    capit_rate: string,
    capital_gain: number,
    cash_$: string,
    cash_flow_$: string,
    cash_flow: number,
    cash_imp: number,
    cash_return: string,
    condo: number,
    cost_seg_period: number,
    cost_seg: number,
    d_payment: number,
    debt_ser: number,
    dep_base: number,
    dol_cred: number,
    dscr: string,
    fed_cap_tax: number,
    grm_factor: number,
    gross_profit: number,
    h_value: number,
    ma_bal: number,
    main_amt: number,
    mgt_fee: number,
    net_cash: number,
    net_equity: number,
    net_profits: number,
    niit_tax: number,
    niittax_rate: number,
    noi: number,
    pdf_bottom: string,
    pdf_head1: string,
    pdf_head2: string,
    pdfmess1: string,
    pdfmess2: string,
    prop_app: number,
    prop_mgt: number,
    r_cash: number,
    recap_rate: number,
    recapture: number,
    rent_increase: number,
    report_years: string,
    return_invest: number,
    roi_return: number,
    seg_dep: number,
    sp: number,
    st_caprate: number,
    st_depre: number,
    state_cap_tax: number,
    state_sel: string,
    t_piti: number,
    tax_due$: string,
    tax_saving: number,
    tax_sit: string,
    temp_cred: string,
    temp_ins: string,
    temp_mi: number,
    temp_pi: string,
    temp_pt: string,
    tot_duct: number,
    total_deprec: number,
    total_taxes: number,
    total_tx_per: string,
    totalcc: number,
    vac_allow: number,
    vacancy: number
}

export type TInvestmentAClose = {
    sp: number,
    area: string,
    state_sel: string,
    current_date: string,
    est_close: string,
    first_payment: string,
    app_fee: number,
    home_ins: number,
    cred_rpt: number,
    flood_cert: number,
    pest_ins: number,
    underfee: number,
    loan_org$: string,
    abs_fee: number,
    clo_fee: number,
    ins_tit: string,
    survey: number,
    int_int: string,
    days_interest: number,
    haz_insur$: string,
    escrow_tax: string,
    clo_tax: string,
    net_tax: string,
    transfer: string,
    docstamp: string,
    mtgetax: string,
    clerk_office: number,
    totalcc: number,
    s_credit$: string,
    l_credit$: string,
    total_cred: number,
    d_payment: number,
    r_cash: number,
    tax_period$: string,
    p_tax_adj$: string,
    tax_escrow_date: string,
    tax_escrow: number
}

export type TInvestmentResponse = {
    meta: TResponseMeta,
    calc: TInvestmentCalc,
    close: TInvestmentClose,
    pdf: TInvestmentPDF,
    aClose: TInvestmentAClose
};
