/*
 * Copyright 2020-2021 AskChristee, LLC. All rights reserved.
 */

import { TResponseMeta } from '.';

export type TVacationCalc = {
  state_sel: string,
  report_type: string,
  fumess: string,
  area: string,
  sp: number,
  ma: number,
  ltv: number,
  total_mtge: number,
  d_payment: number,
  totalcc: number,
  temp_cred: number,
  dol_cred: number,
  r_cash: number,
  temp_rate: number,
  t_piti: number,
  temp_pi: number,
  temp_mi: number,
  temp_pt: number,
  temp_ins: number,
  tot_duct: number,
  net_mort_pay: number,
  print_t_bracket: number,
  tax_saving: number,
  cal_fr: number,
  cal_br: number,
  condo: number,
  report_type_2: string,
  state_select_2: string,
  area_2: string,
  fumess_2: string,
  sp_2: number,
  ma_2: number,
  ltv_2: number,
  total_mtge_2: number,
  d_payment_2: number,
  totalcc_2: number,
  dol_cred_2: number,
  temp_cred_2: number,
  r_cash_2: number,
  temp_rate_2: number,
  t_piti_2: number,
  temp_pi_2: number,
  temp_mi_2: number,
  temp_pt_2: number,
  temp_ins_2: number,
  condo_2: number,
  tot_duct_2: number,
  tax_saving_2: number,
  net_mort_pay_2: number
  ratio_string: string,
  allow_piti: string,
  target_piti: string,
  dol_lend: string,
  temp_lend: string
  t_cash: string,
  ex_cash: string
}

export type TVacationClose = {
  sp: number,
  area: string,
  state_sel: string,
  current_date: string,
  est_close: string,
  first_payment: string,
  app_fee: number,
  home_ins: number,
  cred_rpt: number,
  flood_cert: number,
  pest_ins: number,
  underfee: number,
  loan_org$: string,
  abs_fee: number,
  clo_fee: number,
  ins_tit: string,
  survey: number,
  int_int: string,
  days_interest: number,
  haz_insur$: string,
  escrow_tax: string,
  clo_tax: string,
  net_tax: string,
  transfer: string,
  docstamp: string,
  mtgetax: string,
  clerk_office: number,
  totalcc: number,
  s_credit$: string,
  l_credit$: string,
  total_cred: number,
  d_payment: number,
  r_cash: number,
  tax_period$: string,
  p_tax_adj$: string,
  tax_escrow_date: string,
  tax_escrow: number
}

export type TVacationPdf = {
  pdfmess: string,
  pdf_head1: string,
  pdf_head2: string,
  pdf_head3: string,
  pdf_mess1: string,
  pdf_mess2: string,
  pdf_mess3: string,
  pdf_mess4: string,
  pdf_mess5: string,
  pdf_mess6: string,
  pdf_mess7: string,
  pdf_mess8: string,
  pdf_mess9: string,
  pdf_mess10: string,
  pdf_mess11: string,
  pdf_mess12: string,
  pdf_mess13: string,
  pdf_mess14: string,
  pdf_mess15: string,
  pdf_mess16: string,
  pdf_mess17: string,
  pdf_mess18: string,
  pdf_mess19: string,
  pdf_mess20: string,
  pdf_mess21: string,
  pdf_mess22: string,
  pdf_mess23: string,
  pdf_mess24: string,
  pdf_mess25: string,
  pdf_mess26: string,
  pdf_mess27: string,
  pdf_mess28: string,
  pdf_mess29: string,
  pdf_mess30: string,
}

export type TVacationResults = {
  aCalc1: TVacationCalc | undefined,
  aCalc2: TVacationCalc | undefined,
  aCalc3: TVacationCalc | undefined,
  aCalc4: TVacationCalc | undefined,
  bCalc1: TVacationCalc | undefined,
  bCalc2: TVacationCalc | undefined,
  bCalc3: TVacationCalc | undefined,
  bCalc4: TVacationCalc | undefined,
  aClose1: TVacationClose | undefined,
  aClose2: TVacationClose | undefined,
  aClose3: TVacationClose | undefined,
  aClose4: TVacationClose | undefined,
  bClose1: TVacationClose | undefined,
  bClose2: TVacationClose | undefined,
  bClose3: TVacationClose | undefined,
  bClose4: TVacationClose | undefined,
  aPdf1: TVacationPdf | undefined,
  aPdf2: TVacationPdf | undefined,
  aPdf3: TVacationPdf | undefined,
  aPdf4: TVacationPdf | undefined,
}

export type TVacationResponse = {
  meta: TResponseMeta,
  results: TVacationResults
};
